name: Monitoring CI

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print test message
        run: echo "CI pipeline works!"
